./chech-url.sh    		 http://doi.acm.org/10.1145/2792745.2792766,
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-09-jcp2.pdf
./chech-url.sh    		 https://laszewski.github.io/papers/isj_148.pdf
./chech-url.sh    		 {10.1007/s10586-009-0104-0
./chech-url.sh    		 {10.1109/GreenCom-CPSCom.2010.24
./chech-url.sh     https://laszewski.github.io/papers/laszewski-IEEECloud2012_id-4803.pdf
./chech-url.sh     http://www.nimbusproject.org/downloads/Supporting_Experimental_Computer_Science_final_draft.pdf
./chech-url.sh    		 https://portal.futuresystems.org/
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-12-IEEECloud2012.pdf
./chech-url.sh     http://grids.ucs.indiana.edu/ptliupages/publications/11-imagerepo-cca.pdf
./chech-url.sh     http://grids.ucs.indiana.edu/ptliupages/publications/OGCETG09-1-1.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cog-final.pdf
./chech-url.sh     https://laszewski.github.io/papers/s/vonLaszewski-mobag.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-dtrek.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cacm.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonlaszewski-RSI01.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cog-cpe-final.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-corba.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-greed.pdf
./chech-url.sh    		 https://laszewski.github.io/papers/astro-hpdc10.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cog-pse-final.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cmcs.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cactus5.pdf
./chech-url.sh    		 https://laszewski.github.io/papers/astro-jcc.pdf
./chech-url.sh     https://laszewski.github.io/papers/corbacog-ccpe-gce01-final.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-deploy-32.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-draft-11-imagerepo.pdf
./chech-url.sh    		 https://laszewski.github.io/papers/GCC02_XHe.pdf
./chech-url.sh    		 http://eprints.soton.ac.uk/257752/1/D4.1b_draft.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-infogram.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cog-features.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-ocgsa.pdf
./chech-url.sh     https://laszewski.github.io/papers/plale--pdcs2002.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-perl-cog.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-para4.pdf
./chech-url.sh    		 http://hdl.handle.net/1811/21100
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cmtscience.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-coalloc.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-dublin-core.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-gridftp.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-grid2002book.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-knowledge-grid.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-masses-gcc03.pdf
./chech-url.sh     https://laszewski.github.io/papers//vonLaszewski-qos.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-reputation.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-abstraction-jsa.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-overview-gridftp.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-qos-ccgrid04.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-qos-final-jogc.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-abstracting.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-adhoc-adcom2004.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-clade2004.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-gestalt.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-gridant-hics.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-grid-middleware.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-adhoc-quality.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-scidac-atct.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-ca-workshop.pdf
./chech-url.sh     http://scholarworks.rit.edu/cgi/viewcontent.cgi?article=1977&context=article,
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-exp.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-grid-idea.pdf
./chech-url.sh     http://iopscience.iop.org/1742-6596/16/1/083/pdf/jpconf5_16_083.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-pdcp-reputation.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-workflow-taylor-anl.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-workflow-repository.pdf
./chech-url.sh     http://library.rit.edu/oajournals/index.php/gce/article/view/75/36
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-workflow-book.pdf
./chech-url.sh     http://library.rit.edu/oajournals/index.php/gce/article/view/73/34
./chech-url.sh     http://library.rit.edu/oajournals/index.php/gce/issue/view/10/showToc
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-guss.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-water-iccs.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-work-coordination.pdf
./chech-url.sh     http://library.rit.edu/oajournals/index.php/gce/issue/view/9/showToc
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-torrent.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-07-javascript.pdf
./chech-url.sh     http://library.rit.edu/oajournals/index.php/gce/article/view/85/46
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-08-javascript.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-08-project-ieee.pdf
./chech-url.sh     https://laszewski.github.io/papers/las08msproject.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-ccgrid09-final.pdf
./chech-url.sh    		 https://laszewski.github.io/papers/08-ngc.pdf
./chech-url.sh     https://laszewski.github.io/papers/09-cloudcomp/paper.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-cluster09.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-ispan2.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-09-cuda-biostat-ispa.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-greenit-sla.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-10-ccgrid.pdf
./chech-url.sh    		 https://laszewski.github.io/papers/10-ajy-igcc.pdf
./chech-url.sh    		 https://laszewski.github.io/papers/vonLaszewski-icpp.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-greenit-sla.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-vapl.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-09-aina.pdf
./chech-url.sh     https://laszewski.github.io/papers/las11ann-schedule.pdf
./chech-url.sh     http://scholarworks.rit.edu/cgi/viewcontent.cgi?article=1686&context=article
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-10-CCPE-emolst.pdf
./chech-url.sh     https://laszewski.github.io/papers/11-greenit-bookch.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-11-wtm-hadoop.pdf
./chech-url.sh     http://dl.acm.org/citation.cfm?id=2378975&picked=prox&cfid=389635474&cftoken=32712991
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-12-fg-bookchapter.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-draft-data-analytics-planing.pdf
./chech-url.sh    		 http://doi.acm.org/10.1145/2616498.2616507
./chech-url.sh    		 http://doi.acm.org/10.1145/2609441.2609638
./chech-url.sh     https://github.com/cyberaide/paper-tas-2/raw/master/vonLaszewski-tas-cluster.pdf
./chech-url.sh     https://github.com/cyberaide/paper-tas-2/raw/master/vonLaszewski-tas-cluster.pdf
./chech-url.sh     https://github.com/cyberaide/paper-tas-2/raw/master/vonLaszewski-tas-xsede.pdf
./chech-url.sh     https://laszewski.github.io/papers/10-fg-hypervisor.pdf
./chech-url.sh     https://github.com/cyberaide/paper-tas-2/raw/master/vonLaszewski-tas-cluster.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-tas-xsede.pdf
./chech-url.sh    		 http://tinyurl.com/laszewski-natug
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-ppsn.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-icga.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski94-4dda-design.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-ecwmf-interactive.pdf
./chech-url.sh     https://laszewski.github.io/papers/fitzgerald-hpdc97-mds.pdf
./chech-url.sh     http://www.aps.anl.gov/News/Conferences/1997/nobugs/vonL.html
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-hbm-hpdc.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-hbm-journal.pdf
./chech-url.sh     http://www.startap.net/startap/images/PDF/Foster_IEEEComputer.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-CooperatingJobs.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-siamCmt99.pdf
./chech-url.sh     https://laszewski.github.io/papers/vonLaszewski-spie99.pdf
./chech-url.sh     http://grids.ucs.indiana.edu/ptliupages/presentations/vonLaszewski-10-FG-proj-management.pdf
./chech-url.sh    		 http://sc10.supercomputing.org/?pg=posters.html
./chech-url.sh     http://www.csm.ornl.gov/workshops/DOE_SciDAC/posters.html
./chech-url.sh     http://www.csm.ornl.gov/workshops/DOE_SciDAC/posters.html
./chech-url.sh    		 http://www.csm.ornl.gov/workshops/SciDAC2005/
